# Generated by Django 5.0.6 on 2024-05-29 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permissible_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='gis.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Pollution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField()),
                ('coordinates', models.JSONField()),
                ('label', models.CharField(max_length=255)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollutions', to='gis.substance')),
            ],
        ),
        migrations.CreateModel(
            name='Indications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_indication', models.DateTimeField()),
                ('concentration', models.FloatField()),
                ('wind_degree', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indications', to='gis.sensor')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indications', to='gis.substance')),
            ],
        ),
    ]
